score: 3
review-score: 4
accepted:
  - github.com/dbeliakov/mipt-golang-tasks--2022
  - github.com/aii23/MiptGolang
  - github.com/Vulp1x/mipt-golang
  - github.com/webostap/mipt-golang
  - github.com/r-vlasov/mipt_golang
  - github.com/cosmicNebular/mipt_golang
  - github.com/Vulp1x/mipt-golang
